/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-actuator:3.5.0")
    api("org.springframework.boot:spring-boot-starter-web:3.5.0")
    api("org.postgresql:postgresql:42.7.6")
    api("org.springframework.modulith:spring-modulith-api:1.4.0")
    api("org.springframework.modulith:spring-modulith-starter-core:1.4.0")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24")
    api("org.jetbrains.kotlin:kotlin-reflect:1.9.24")
    api("org.jetbrains.kotlin:kotlin-maven-allopen:1.9.24")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.5.0")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.9.24")
}

group = "de.btm"
version = "1.0-SNAPSHOT"
description = "backend"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
